### PR TITLE
added Installing Packages

### PR DESCRIPTION
**Pull request by Azrael-1123**

### CODE REVIEW

**Comment by DeflatedPickle** [comment]
- "Python" is the name of the language, capitalise it.
- Make note of having to have Python in the system PATH to be able to use the "python" command
- Make a note that you can upgrade packages with the `--upgrade` flag.
- You don't have to write the "python" command, you can just do "pip install".
- The last part is unnecessary, it's unpythonic.
- This book is Markdown, make use of code blocks and inline code rather than quoting the command.
- Don't mention the Python versions PIP is included with, this is a guide for Python 3.6.

**Comment by Azrael-1123** [comment]
so since I'm kind of dumb and don't know how to edit pr's, Imma just make a new one lul

**Comment by DeflatedPickle** [comment]
Don't bother, I already wrote a better section and published it.

**Comment by Azrael-1123** [comment]
oh ok then

**Comment by Azrael-1123** [comment]
the only Thing I can see could be slightly better is that you could add the uninstlal part, but otherwise well done

**Pull request closed without merging**
